import { writable } from 'svelte/store'

export const api_url = writable("http://localhost:5104/api/v1/")
export const api_token = writable("eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0MCIsImp0aSI6IjhjNzZkZjlhLTEzMjQtNDg3My1iNjgxLTczZGFmODZjNjU4MSIsImlhdCI6IjIwLzEyLzIwMjMgMTE6MjU6NDUiLCJuYW1lIjoiVmlhZ2VucyIsInVuaXF1ZV9uYW1lIjoiNDAiLCJlbWFpbCI6IiIsImdpdmVuX25hbWUiOiJVc2VyIiwiZmFtaWx5X25hbWUiOiI1IiwiZXhwIjoxNzAzMDc4NzQ1LCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjUxMDQiLCJhdWQiOiJodHRwOi8vbG9jYWxob3N0OjUxNzMifQ.7DYSMBK87_CMDmGY9Gm-1ruOeqoMqJ_Wkh1rcfd-ei0")