import { writable } from 'svelte/store'

export const api_url = writable("http://localhost:5104/api/v1/")
export const api_token = writable("eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwianRpIjoiN2E2NTJhOTUtNmE5Mi00OWJmLTk4MDgtOTJkOTQ1ZWViMzRiIiwiaWF0IjoiMTYvMDEvMjAyNCAxNjoyMToyNyIsIm5hbWUiOiJBZG1pbmlzdHJhZG9yIiwiVXNlcklkIjoiMSIsImVtYWlsIjoiIiwiVXNlclR5cGUiOiJTbWFydFRpbWVVc2VyIiwiVXNlclByb2ZpbGVJZCI6IiIsImV4cCI6MTcwNTQyOTI4NywiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo1MTA0IiwiYXVkIjoiaHR0cDovL2xvY2FsaG9zdDo1MTczIn0.NJuHDqExT2MTjJxavKOrjOv_Az-3XAzZoNkEwP-AwWY")