import { writable } from 'svelte/store'

export const api_url = writable("http://localhost:5104/api/v1/")
export const api_token = writable("eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0MCIsImp0aSI6IjJhZjBlNDk1LTgxMDUtNGY0NS04ZTE1LTBkZWQyZWVkM2QwZiIsImlhdCI6IjIyLzEyLzIwMjMgMDk6MTY6MDgiLCJuYW1lIjoiVmlhZ2VucyIsInVuaXF1ZV9uYW1lIjoiNDAiLCJlbWFpbCI6IiIsImdpdmVuX25hbWUiOiJVc2VyIiwiZmFtaWx5X25hbWUiOiI1IiwiZXhwIjoxNzAzMjQzNzY4LCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjUxMDQiLCJhdWQiOiJodHRwOi8vbG9jYWxob3N0OjUxNzMifQ.JpcyMJS__Q48UHR7CImx0ol94LaLrtXkYtOBVijNiGE")