// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'pt'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	Sidebar: {
		/**
		 * R​e​v​i​e​w​s
		 */
		Reviews: string
		/**
		 * F​o​r​m​s
		 */
		Forms: string
		/**
		 * S​t​a​t​i​s​t​i​c​s
		 */
		Statistics: string
	}
	/**
	 * C​r​e​a​t​e​ ​r​e​v​i​e​w
	 */
	ReviewButton: string
	/**
	 * C​r​e​a​t​e​ ​n​e​w​ ​r​e​v​i​e​w
	 */
	NewReviewTitle: string
	/**
	 * P​e​r​f​o​r​m​a​n​c​e​ ​m​o​d​u​l​e
	 */
	PerformanceModule: string
	/**
	 * H​e​l​l​o
	 */
	Hello: string
	/**
	 * C​r​e​a​t​e​ ​f​o​r​m
	 */
	FormButton: string
	/**
	 * S​e​a​r​c​h​ ​f​o​r​ ​t​h​e​ ​n​a​m​e​ ​o​f​ ​t​h​e​ ​d​e​p​a​r​t​m​e​n​t​ ​t​o​ ​f​i​l​t​e​r​ ​t​h​e​ ​l​i​s​t
	 */
	FormSearchInput: string
	/**
	 * C​r​e​a​t​e​ ​f​o​r​m​ ​m​o​d​e​l
	 */
	CreateFormModel: string
	/**
	 * T​h​i​s​ ​f​e​a​t​u​r​e​ ​a​l​l​o​w​s​ ​t​h​e​ ​c​r​e​a​t​i​o​n​ ​o​f​ ​f​o​r​m​ ​t​e​m​p​l​a​t​e​s​,​ ​e​s​t​a​b​l​i​s​h​i​n​g​ ​p​r​e​d​e​f​i​n​e​d​ ​s​t​r​u​c​t​u​r​e​s​ ​f​o​r​ ​f​u​t​u​r​e​ ​r​e​v​i​e​w​s​.​ ​S​i​m​p​l​i​f​y​ ​t​h​e​ ​a​s​s​e​s​s​m​e​n​t​ ​p​r​o​c​e​s​s​ ​b​y​ ​c​r​e​a​t​i​n​g​ ​c​o​n​s​i​s​t​e​n​t​ ​p​a​t​t​e​r​n​s​,​ ​s​a​v​i​n​g​ ​t​i​m​e​,​ ​a​n​d​ ​m​a​i​n​t​a​i​n​i​n​g​ ​u​n​i​f​o​r​m​i​t​y​ ​i​n​ ​e​v​a​l​u​a​t​i​o​n​s​.
	 */
	CreateFormModelDescription: string
	/**
	 * Y​o​u​r​ ​W​o​r​k
	 */
	YourWork: string
	/**
	 * C​r​e​a​t​e​ ​b​l​a​n​k​ ​r​e​v​i​e​w
	 */
	CreateBlankReview: string
	/**
	 * C​o​p​y​ ​f​o​r​m​ ​m​o​d​e​l
	 */
	CopyFormModel: string
	/**
	 * C​r​i​a​ ​u​m​a​ ​r​e​v​i​s​ã​o​ ​v​a​z​i​a​,​ ​p​e​r​m​i​t​e​ ​a​ ​a​d​i​ç​ã​o​ ​d​e​ ​q​u​e​s​t​õ​e​s​,​ ​a​s​s​o​c​i​a​ç​ã​o​ ​d​o​ ​t​i​p​o​ ​d​e​ ​r​e​v​i​s​ã​o​,​ ​e​s​p​e​c​i​f​i​c​a​ç​ã​o​ ​d​o​ ​r​e​s​p​o​n​s​á​v​e​l​,​ ​d​a​t​a​ ​d​e​ ​i​n​í​c​i​o​ ​e​ ​t​é​r​m​i​n​o​.
	 */
	CreateBlankReviewDescription: string
	/**
	 * C​r​i​a​ ​u​m​a​ ​r​e​v​i​s​ã​o​ ​p​r​e​e​n​c​h​i​d​a​ ​c​o​m​ ​u​m​ ​m​o​d​e​l​o​ ​d​e​ ​f​o​r​m​u​l​á​r​i​o​ ​q​u​e​ ​i​n​c​l​u​i​ ​q​u​e​s​t​õ​e​s​ ​p​r​é​-​d​e​f​i​n​i​d​a​s​.
	 */
	CopyFormModelDescription: string
	/**
	 * S​h​o​w​ ​s​i​d​e​b​a​r
	 */
	ShowSidebar: string
	/**
	 * H​i​d​e​ ​s​i​d​e​b​a​r
	 */
	HideSidebar: string
	/**
	 * S​e​t​t​i​n​g​s
	 */
	Settings: string
}

export type TranslationFunctions = {
	Sidebar: {
		/**
		 * Reviews
		 */
		Reviews: () => LocalizedString
		/**
		 * Forms
		 */
		Forms: () => LocalizedString
		/**
		 * Statistics
		 */
		Statistics: () => LocalizedString
	}
	/**
	 * Create review
	 */
	ReviewButton: () => LocalizedString
	/**
	 * Create new review
	 */
	NewReviewTitle: () => LocalizedString
	/**
	 * Performance module
	 */
	PerformanceModule: () => LocalizedString
	/**
	 * Hello
	 */
	Hello: () => LocalizedString
	/**
	 * Create form
	 */
	FormButton: () => LocalizedString
	/**
	 * Search for the name of the department to filter the list
	 */
	FormSearchInput: () => LocalizedString
	/**
	 * Create form model
	 */
	CreateFormModel: () => LocalizedString
	/**
	 * This feature allows the creation of form templates, establishing predefined structures for future reviews. Simplify the assessment process by creating consistent patterns, saving time, and maintaining uniformity in evaluations.
	 */
	CreateFormModelDescription: () => LocalizedString
	/**
	 * Your Work
	 */
	YourWork: () => LocalizedString
	/**
	 * Create blank review
	 */
	CreateBlankReview: () => LocalizedString
	/**
	 * Copy form model
	 */
	CopyFormModel: () => LocalizedString
	/**
	 * Cria uma revisão vazia, permite a adição de questões, associação do tipo de revisão, especificação do responsável, data de início e término.
	 */
	CreateBlankReviewDescription: () => LocalizedString
	/**
	 * Cria uma revisão preenchida com um modelo de formulário que inclui questões pré-definidas.
	 */
	CopyFormModelDescription: () => LocalizedString
	/**
	 * Show sidebar
	 */
	ShowSidebar: () => LocalizedString
	/**
	 * Hide sidebar
	 */
	HideSidebar: () => LocalizedString
	/**
	 * Settings
	 */
	Settings: () => LocalizedString
}

export type Formatters = {}
