// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'pt'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	Sidebar: {
		/**
		 * R​e​v​i​e​w​s
		 */
		Reviews: string
		/**
		 * F​o​r​m​s
		 */
		Forms: string
		/**
		 * S​t​a​t​i​s​t​i​c​s
		 */
		Statistics: string
	}
	/**
	 * C​r​e​a​t​e​ ​r​e​v​i​e​w
	 */
	ReviewButton: string
	/**
	 * C​r​e​a​t​e​ ​n​e​w​ ​r​e​v​i​e​w
	 */
	NewReviewTitle: string
	/**
	 * P​e​r​f​o​r​m​a​n​c​e​ ​m​o​d​u​l​e
	 */
	PerformanceModule: string
	/**
	 * H​e​l​l​o
	 */
	Hello: string
	/**
	 * C​r​e​a​t​e​ ​f​o​r​m
	 */
	FormButton: string
	/**
	 * I​n​s​e​r​t​ ​t​h​e​ ​t​i​t​l​e​ ​o​f​ ​t​h​e​ ​f​o​r​m​ ​t​e​m​p​l​a​t​e​ ​t​o​ ​f​i​l​t​e​r​ ​t​h​e​ ​l​i​s​t
	 */
	FormSearchInput: string
	/**
	 * C​r​e​a​t​e​ ​f​o​r​m​ ​m​o​d​e​l
	 */
	CreateFormModel: string
	/**
	 * T​h​i​s​ ​f​e​a​t​u​r​e​ ​a​l​l​o​w​s​ ​t​h​e​ ​c​r​e​a​t​i​o​n​ ​o​f​ ​f​o​r​m​ ​t​e​m​p​l​a​t​e​s​,​ ​e​s​t​a​b​l​i​s​h​i​n​g​ ​p​r​e​d​e​f​i​n​e​d​ ​s​t​r​u​c​t​u​r​e​s​ ​f​o​r​ ​f​u​t​u​r​e​ ​r​e​v​i​e​w​s​.​ ​S​i​m​p​l​i​f​y​ ​t​h​e​ ​a​s​s​e​s​s​m​e​n​t​ ​p​r​o​c​e​s​s​ ​b​y​ ​c​r​e​a​t​i​n​g​ ​c​o​n​s​i​s​t​e​n​t​ ​p​a​t​t​e​r​n​s​,​ ​s​a​v​i​n​g​ ​t​i​m​e​,​ ​a​n​d​ ​m​a​i​n​t​a​i​n​i​n​g​ ​u​n​i​f​o​r​m​i​t​y​ ​i​n​ ​e​v​a​l​u​a​t​i​o​n​s​.
	 */
	CreateFormModelDescription: string
	/**
	 * Y​o​u​r​ ​W​o​r​k
	 */
	YourWork: string
	/**
	 * C​r​e​a​t​e​ ​b​l​a​n​k​ ​r​e​v​i​e​w
	 */
	CreateBlankReview: string
	/**
	 * C​o​p​y​ ​f​o​r​m​ ​m​o​d​e​l
	 */
	CopyFormModel: string
	/**
	 * C​r​e​a​t​e​ ​a​n​ ​e​m​p​t​y​ ​r​e​v​i​e​w​,​ ​t​h​a​t​ ​a​l​l​o​w​s​ ​a​d​d​i​n​g​ ​q​u​e​s​t​i​o​n​s​,​ ​a​s​s​o​c​i​a​t​e​ ​t​h​e​ ​r​e​v​i​e​w​ ​t​y​p​e​,​ ​s​p​e​c​i​f​y​ ​t​h​e​ ​r​e​s​p​o​n​s​a​b​l​e​ ​a​n​d​ ​s​t​a​r​t​ ​a​n​d​ ​e​n​d​ ​d​a​t​e​.
	 */
	CreateBlankReviewDescription: string
	/**
	 * C​r​e​a​t​e​ ​a​ ​r​e​v​i​e​w​ ​w​i​t​h​ ​a​ ​f​o​r​m​ ​t​e​m​p​l​a​t​e​ ​t​h​a​t​ ​i​n​c​l​u​d​e​s​ ​p​r​e​d​e​f​i​n​e​d​ ​q​u​e​s​t​i​o​n​s​.
	 */
	CopyFormModelDescription: string
	/**
	 * S​h​o​w​ ​s​i​d​e​b​a​r
	 */
	ShowSidebar: string
	/**
	 * H​i​d​e​ ​s​i​d​e​b​a​r
	 */
	HideSidebar: string
	/**
	 * S​e​t​t​i​n​g​s
	 */
	Settings: string
	/**
	 * P​r​e​v​i​e​w
	 */
	Preview: string
	/**
	 * D​e​t​a​i​l​s
	 */
	Details: string
	/**
	 * Q​u​e​s​t​i​o​n​s
	 */
	Questions: string
	/**
	 * F​i​n​a​l​i​z​e
	 */
	Finalize: string
	/**
	 * C​h​o​o​s​e​ ​a​ ​l​a​n​g​u​a​g​e
	 */
	ChooseLanguage: string
	/**
	 * P​o​r​t​u​g​u​e​s​e
	 */
	Portuguese: string
	/**
	 * E​n​g​l​i​s​h
	 */
	English: string
	/**
	 * F​r​e​n​c​h
	 */
	French: string
	/**
	 * S​p​a​n​i​s​h
	 */
	Spanish: string
	/**
	 * P​o​l​i​s​h
	 */
	Polish: string
	QuestionType: {
		/**
		 * T​e​x​t
		 */
		Text: string
		/**
		 * S​i​n​g​l​e​C​h​o​i​c​e
		 */
		SingleChoice: string
		/**
		 * R​a​t​i​n​g
		 */
		Rating: string
	}
	/**
	 * T​i​t​l​e
	 */
	Title: string
	/**
	 * D​e​s​c​r​i​p​t​i​o​n
	 */
	Description: string
	/**
	 * I​n​s​e​r​t​ ​t​h​e​ ​t​i​t​l​e​ ​o​f​ ​t​h​e​ ​r​e​v​i​e​w​ ​t​o​ ​f​i​l​t​e​r​ ​t​h​e​ ​l​i​s​t
	 */
	ReviewSearchInput: string
	/**
	 * O​n​g​o​i​n​g
	 */
	Ongoing: string
	/**
	 * C​o​m​p​l​e​t​e​d
	 */
	Completed: string
	/**
	 * N​o​t​ ​s​t​a​r​t​e​d
	 */
	NotStarted: string
	/**
	 * C​a​n​c​e​l​e​d
	 */
	Canceled: string
	/**
	 * S​t​a​t​e
	 */
	State: string
	/**
	 * E​n​d​i​n​g​ ​d​a​t​e
	 */
	EndingDate: string
	/**
	 * P​r​o​g​r​e​s​s​i​o​n
	 */
	Progression: string
	/**
	 * F​o​r​m​ ​m​o​d​e​l​ ​t​i​t​l​e
	 */
	FormModelTitleTitle: string
	/**
	 * I​n​s​e​r​t​ ​a​ ​t​i​t​l​e​ ​f​o​r​ ​t​h​e​ ​f​o​r​m​ ​m​o​d​e​l​.
	 */
	FormModelTitleDescription: string
	/**
	 * F​o​r​m​ ​m​o​d​e​l​ ​d​e​s​c​r​i​p​t​i​o​n
	 */
	FormModelDescriptionTitle: string
	/**
	 * A​d​d​ ​a​ ​b​r​i​e​f​ ​d​e​s​c​r​i​p​t​i​o​n​ ​t​h​a​t​ ​h​i​g​h​l​i​g​h​t​s​ ​t​h​e​ ​p​u​r​p​o​s​e​ ​o​r​ ​c​o​n​t​e​n​t​ ​o​f​ ​t​h​e​ ​m​o​d​e​l​.​ ​T​h​i​s​ ​w​i​l​l​ ​h​e​l​p​ ​p​r​o​v​i​d​e​ ​a​d​d​i​t​i​o​n​a​l​ ​g​u​i​d​a​n​c​e​ ​o​n​ ​t​h​e​ ​f​o​r​m​ ​w​h​e​n​ ​s​e​l​e​c​t​i​n​g​ ​i​t​ ​f​o​r​ ​r​e​v​i​e​w​.
	 */
	FormModelDescriptionDescription: string
	/**
	 * R​e​t​u​r​n
	 */
	Return: string
	/**
	 * F​o​r​w​a​r​d
	 */
	Forward: string
	/**
	 * T​y​p​e​ ​o​f​ ​Q​u​e​s​t​i​o​n
	 */
	QuestionTypeText: string
	/**
	 * F​o​r​m​ ​P​r​e​v​i​e​w
	 */
	FormPreview: string
	/**
	 * Q​u​e​s​t​i​o​n​ ​P​r​o​p​e​r​t​i​e​s
	 */
	QuestionProperties: string
	/**
	 * N​o​ ​q​u​e​s​t​i​o​n​s​ ​y​e​t​,​ ​d​r​a​g​ ​o​n​e​ ​t​y​p​e​ ​o​f​ ​q​u​e​s​t​i​o​n​ ​t​o​ ​a​d​d​ ​a​ ​q​u​e​s​t​i​o​n​ ​t​o​ ​t​h​i​s​ ​f​o​r​m​.
	 */
	FormPreviewPlaceholder: string
	/**
	 * N​o​ ​r​a​t​i​n​g​ ​o​p​t​i​o​n​ ​a​n​s​w​e​r​s​ ​y​e​t​.
	 */
	FormPreviewRatingPlaceholder: string
	/**
	 * N​o​ ​s​i​n​g​l​e​ ​c​h​o​i​c​e​ ​o​p​t​i​o​n​ ​a​n​s​w​e​r​s​ ​y​e​t​.
	 */
	FormPreviewSingleChoicePlaceholder: string
	/**
	 * A​n​s​w​e​r
	 */
	Answer: string
	/**
	 * R​e​q​u​i​r​e​d
	 */
	Required: string
	/**
	 * A​n​s​w​e​r​s
	 */
	Answers: string
	/**
	 * N​u​m​e​r​i​c
	 */
	Numeric: string
	/**
	 * A​d​d​ ​a​n​ ​o​p​t​i​o​n
	 */
	AddOption: string
	/**
	 * S​i​n​g​l​e​ ​C​h​o​i​c​e​ ​o​p​t​i​o​n​ ​m​u​s​t​ ​h​a​v​e​ ​a​ ​t​e​x​t
	 */
	AddSingleChoiceOptionError: string
	/**
	 * A​l​l​ ​f​i​e​l​d​s​ ​m​u​s​t​ ​b​e​ ​f​i​l​l​e​d
	 */
	AddRatingOptionError01: string
	/**
	 * A​ ​r​a​t​i​n​g​ ​o​p​t​i​o​n​ ​f​o​r​ ​t​h​i​s​ ​n​u​m​b​e​r​ ​a​l​r​e​a​d​y​ ​e​x​i​s​t​s
	 */
	AddRatingOptionError02: string
	/**
	 * F​o​r​m​ ​T​e​m​p​l​a​t​e​ ​c​r​e​a​t​e​d​ ​s​u​c​c​e​s​s​f​u​l​l​y
	 */
	FormTemplateSuccess: string
}

export type TranslationFunctions = {
	Sidebar: {
		/**
		 * Reviews
		 */
		Reviews: () => LocalizedString
		/**
		 * Forms
		 */
		Forms: () => LocalizedString
		/**
		 * Statistics
		 */
		Statistics: () => LocalizedString
	}
	/**
	 * Create review
	 */
	ReviewButton: () => LocalizedString
	/**
	 * Create new review
	 */
	NewReviewTitle: () => LocalizedString
	/**
	 * Performance module
	 */
	PerformanceModule: () => LocalizedString
	/**
	 * Hello
	 */
	Hello: () => LocalizedString
	/**
	 * Create form
	 */
	FormButton: () => LocalizedString
	/**
	 * Insert the title of the form template to filter the list
	 */
	FormSearchInput: () => LocalizedString
	/**
	 * Create form model
	 */
	CreateFormModel: () => LocalizedString
	/**
	 * This feature allows the creation of form templates, establishing predefined structures for future reviews. Simplify the assessment process by creating consistent patterns, saving time, and maintaining uniformity in evaluations.
	 */
	CreateFormModelDescription: () => LocalizedString
	/**
	 * Your Work
	 */
	YourWork: () => LocalizedString
	/**
	 * Create blank review
	 */
	CreateBlankReview: () => LocalizedString
	/**
	 * Copy form model
	 */
	CopyFormModel: () => LocalizedString
	/**
	 * Create an empty review, that allows adding questions, associate the review type, specify the responsable and start and end date.
	 */
	CreateBlankReviewDescription: () => LocalizedString
	/**
	 * Create a review with a form template that includes predefined questions.
	 */
	CopyFormModelDescription: () => LocalizedString
	/**
	 * Show sidebar
	 */
	ShowSidebar: () => LocalizedString
	/**
	 * Hide sidebar
	 */
	HideSidebar: () => LocalizedString
	/**
	 * Settings
	 */
	Settings: () => LocalizedString
	/**
	 * Preview
	 */
	Preview: () => LocalizedString
	/**
	 * Details
	 */
	Details: () => LocalizedString
	/**
	 * Questions
	 */
	Questions: () => LocalizedString
	/**
	 * Finalize
	 */
	Finalize: () => LocalizedString
	/**
	 * Choose a language
	 */
	ChooseLanguage: () => LocalizedString
	/**
	 * Portuguese
	 */
	Portuguese: () => LocalizedString
	/**
	 * English
	 */
	English: () => LocalizedString
	/**
	 * French
	 */
	French: () => LocalizedString
	/**
	 * Spanish
	 */
	Spanish: () => LocalizedString
	/**
	 * Polish
	 */
	Polish: () => LocalizedString
	QuestionType: {
		/**
		 * Text
		 */
		Text: () => LocalizedString
		/**
		 * SingleChoice
		 */
		SingleChoice: () => LocalizedString
		/**
		 * Rating
		 */
		Rating: () => LocalizedString
	}
	/**
	 * Title
	 */
	Title: () => LocalizedString
	/**
	 * Description
	 */
	Description: () => LocalizedString
	/**
	 * Insert the title of the review to filter the list
	 */
	ReviewSearchInput: () => LocalizedString
	/**
	 * Ongoing
	 */
	Ongoing: () => LocalizedString
	/**
	 * Completed
	 */
	Completed: () => LocalizedString
	/**
	 * Not started
	 */
	NotStarted: () => LocalizedString
	/**
	 * Canceled
	 */
	Canceled: () => LocalizedString
	/**
	 * State
	 */
	State: () => LocalizedString
	/**
	 * Ending date
	 */
	EndingDate: () => LocalizedString
	/**
	 * Progression
	 */
	Progression: () => LocalizedString
	/**
	 * Form model title
	 */
	FormModelTitleTitle: () => LocalizedString
	/**
	 * Insert a title for the form model.
	 */
	FormModelTitleDescription: () => LocalizedString
	/**
	 * Form model description
	 */
	FormModelDescriptionTitle: () => LocalizedString
	/**
	 * Add a brief description that highlights the purpose or content of the model. This will help provide additional guidance on the form when selecting it for review.
	 */
	FormModelDescriptionDescription: () => LocalizedString
	/**
	 * Return
	 */
	Return: () => LocalizedString
	/**
	 * Forward
	 */
	Forward: () => LocalizedString
	/**
	 * Type of Question
	 */
	QuestionTypeText: () => LocalizedString
	/**
	 * Form Preview
	 */
	FormPreview: () => LocalizedString
	/**
	 * Question Properties
	 */
	QuestionProperties: () => LocalizedString
	/**
	 * No questions yet, drag one type of question to add a question to this form.
	 */
	FormPreviewPlaceholder: () => LocalizedString
	/**
	 * No rating option answers yet.
	 */
	FormPreviewRatingPlaceholder: () => LocalizedString
	/**
	 * No single choice option answers yet.
	 */
	FormPreviewSingleChoicePlaceholder: () => LocalizedString
	/**
	 * Answer
	 */
	Answer: () => LocalizedString
	/**
	 * Required
	 */
	Required: () => LocalizedString
	/**
	 * Answers
	 */
	Answers: () => LocalizedString
	/**
	 * Numeric
	 */
	Numeric: () => LocalizedString
	/**
	 * Add an option
	 */
	AddOption: () => LocalizedString
	/**
	 * Single Choice option must have a text
	 */
	AddSingleChoiceOptionError: () => LocalizedString
	/**
	 * All fields must be filled
	 */
	AddRatingOptionError01: () => LocalizedString
	/**
	 * A rating option for this number already exists
	 */
	AddRatingOptionError02: () => LocalizedString
	/**
	 * Form Template created successfully
	 */
	FormTemplateSuccess: () => LocalizedString
}

export type Formatters = {}
